add nested field validation
jellydator/validation pull request #6
Opened 2023-01-03 08:51 UTC by TcMits

Resolved #1

2023-01-06 00:39 UTC, slessard commented
How does this solution work with one additional level of nesting?

type Abc struct {
    A int
    B struct {
        C struct {
            D int
        }
    }
}

2023-01-06 04:31 UTC, TcMits commented
> How does this solution work with one additional level of nesting?
@slessard 
```go
  m := struct {
    A int
    B struct {
        C struct {
            D string
        }
    }
  }{}

  err := ValidateStruct(
    &m, 
    FieldStruct(
      &m.B,
      FieldStruct(
        &m.B.C,
        Field(
          &m.B.C.D,
          Required,
        ),
      ),
    ),
  )
```

2023-01-06 07:37 UTC, TcMits commented
> does this PR includes the cache?

@bokunodev No, i will consider cache solution in after this PR. But i think maintainer is not active yet 😄

2023-01-10 10:13 UTC, swithek commented on struct.go
> +// Field specifies a struct field and the corresponding validation field rules.
`Field` -> `FieldStruct`

2023-01-10 10:25 UTC, swithek requested changes
Looks good! Only one small change needs to be made.

2023-01-10 11:21 UTC, swithek approved these changes

2023-01-10 11:22 UTC, merged